In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('Absenteeism_preprocessed.csv')
data

Reason1  Reason2  Reason3  Reason4  Month  Day of the week  \
0          0        0        0        1      7                1   
1          0        0        0        0      7                1   
2          0        0        0        1      7                2   
3          1        0        0        0      7                3   
4          0        0        0        1      7                3   
..       ...      ...      ...      ...    ...              ...   
695        1        0        0        0      5                2   
696        1        0        0        0      5                2   
697        1        0        0        0      5                3   
698        0        0        0        1      5                3   
699        0        0        0        1      5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          4  
1                 31          0         1     0                          0  
2                 31          0         0     0                          2  
3                 24          0         2     0                          4  
4                 30          0         2     1                          2  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2  

[700 rows x 15 columns]

In [3]:
#.median measures the Median of a certain column values
#<=3: Moderately Absent
#>=4: Excessively Absent
data['Absenteeism Time in Hours'].median()

3.0

In [4]:
data['Absenteeism Time in Hours'].unique()

array([  4,   0,   2,   8,  40,   1,   7,   3,  32,   5,  16,  24,  64,
        56,  80, 120, 112, 104,  48], dtype=int64)

np.where(condition,value if True, value if False) checks if a condition has been satisfied assigns a value accordingly

In [5]:
#Supervised Machine Learning has 0 or 1
#Kondisi: Kalau ada VALUE di column ATiH >3 maka
#Kalau TRUE >3, jadikan value 1
#Kalau FALSE <3, jadikan value 0

targets=np.where(data['Absenteeism Time in Hours']>3,1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data['Targets']=targets
data

Reason1  Reason2  Reason3  Reason4  Month  Day of the week  \
0          0        0        0        1      7                1   
1          0        0        0        0      7                1   
2          0        0        0        1      7                2   
3          1        0        0        0      7                3   
4          0        0        0        1      7                3   
..       ...      ...      ...      ...    ...              ...   
695        1        0        0        0      5                2   
696        1        0        0        0      5                2   
697        1        0        0        0      5                3   
698        0        0        0        1      5                3   
699        0        0        0        1      5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     Targets  
0          1  
1          0  
2          0  
3          1  
4          0  
..       ...  
695        1  
696        0  
697        1  
698        0  
699        0  

[700 rows x 16 columns]

In [7]:
#46% targets are 1
#54% targets are 0
#60-40 data cukup for Logistic Regression
#55-45 is ideal
targets.sum()/targets.shape[0]

0.45571428571428574

In [57]:
new_data=data.copy()
new_data=new_data.drop(['Absenteeism Time in Hours','Day of the week','Daily Work Load Average','Distance to Work'],axis=1)
new_data

Reason1  Reason2  Reason3  Reason4  Month  Transportation Expense  Age  \
0          0        0        0        1      7                     289   33   
1          0        0        0        0      7                     118   50   
2          0        0        0        1      7                     179   38   
3          1        0        0        0      7                     279   39   
4          0        0        0        1      7                     289   33   
..       ...      ...      ...      ...    ...                     ...  ...   
695        1        0        0        0      5                     179   40   
696        1        0        0        0      5                     225   28   
697        1        0        0        0      5                     330   28   
698        0        0        0        1      5                     235   32   
699        0        0        0        1      5                     291   40   

     Body Mass Index  Education  Children  Pets  Targets  
0                 30          0         2     1        1  
1                 31          0         1     0        0  
2                 31          0         0     0        0  
3                 24          0         2     0        1  
4                 30          0         2     1        0  
..               ...        ...       ...   ...      ...  
695               22          1         2     0        1  
696               24          0         1     2        0  
697               25          1         0     0        1  
698               25          1         0     0        0  
699               25          0         1     1        0  

[700 rows x 12 columns]

In [58]:
new_data.shape

(700, 12)

DataFrame.iloc[row indices,column indices]

In [60]:
#ILOC EXCLUDES ENDING INDEX
new_data.iloc[:,0:11]

Reason1  Reason2  Reason3  Reason4  Month  Transportation Expense  Age  \
0          0        0        0        1      7                     289   33   
1          0        0        0        0      7                     118   50   
2          0        0        0        1      7                     179   38   
3          1        0        0        0      7                     279   39   
4          0        0        0        1      7                     289   33   
..       ...      ...      ...      ...    ...                     ...  ...   
695        1        0        0        0      5                     179   40   
696        1        0        0        0      5                     225   28   
697        1        0        0        0      5                     330   28   
698        0        0        0        1      5                     235   32   
699        0        0        0        1      5                     291   40   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 11 columns]

In [61]:
inputs=new_data.iloc[:,:-1]
inputs

Reason1  Reason2  Reason3  Reason4  Month  Transportation Expense  Age  \
0          0        0        0        1      7                     289   33   
1          0        0        0        0      7                     118   50   
2          0        0        0        1      7                     179   38   
3          1        0        0        0      7                     279   39   
4          0        0        0        1      7                     289   33   
..       ...      ...      ...      ...    ...                     ...  ...   
695        1        0        0        0      5                     179   40   
696        1        0        0        0      5                     225   28   
697        1        0        0        0      5                     330   28   
698        0        0        0        1      5                     235   32   
699        0        0        0        1      5                     291   40   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 11 columns]

In [62]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler=StandardScaler(copy,with_mean,with_std)
        self.columns=columns
        self.mean_=None
        self.var_=None
    
    def fit(self,x,y=None):
        self.scaler.fit(x[self.columns],y)
        self.mean_=np.mean(x[self.columns])
        self.var_=np.var(x[self.columns])
        return self
    
    def transform(self,x,y=None,copy=None):
        init_col_order=x.columns
        x_scaled=pd.DataFrame(self.scaler.transform(x[self.columns]),columns=self.columns)
        x_not_scaled=x.loc[:,~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled,x_scaled],axis=1)[init_col_order]

In [63]:
CustomScaler

__main__.CustomScaler

In [64]:
inputs.columns.values

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [66]:
column_name=[ 'Month', 'Transportation Expense','Age', 'Body Mass Index', 'Children', 'Pets']
abs_scaler=CustomScaler(column_name)
abs_scaler.fit(inputs)

D:\SEM 4\Anaconda\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [67]:
scaled_inputs=abs_scaler.transform(inputs)
scaled_inputs

Reason1  Reason2  Reason3  Reason4     Month  Transportation Expense  \
0          0        0        0        1  0.182726                1.005844   
1          0        0        0        0  0.182726               -1.574681   
2          0        0        0        1  0.182726               -0.654143   
3          1        0        0        0  0.182726                0.854936   
4          0        0        0        1  0.182726                1.005844   
..       ...      ...      ...      ...       ...                     ...   
695        1        0        0        0 -0.388293               -0.654143   
696        1        0        0        0 -0.388293                0.040034   
697        1        0        0        0 -0.388293                1.624567   
698        0        0        0        1 -0.388293                0.190942   
699        0        0        0        1 -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

In [68]:
from sklearn.model_selection import train_test_split
train_test_split(scaled_inputs,targets)

[     Reason1  Reason2  Reason3  Reason4     Month  Transportation Expense  \
 30         0        0        1        0  0.468236               -0.654143   
 520        0        0        0        1  1.039256               -0.654143   
 693        1        0        0        0 -0.388293                0.190942   
 73         0        0        0        1  1.039256                0.040034   
 279        1        0        0        0  0.753746                0.356940   
 ..       ...      ...      ...      ...       ...                     ...   
 276        0        0        0        0  0.753746                0.130578   
 380        0        0        0        1 -1.244823               -0.503235   
 585        1        0        0        0 -1.244823               -0.654143   
 537        0        0        0        1  1.324766                1.005844   
 104        0        0        1        0  1.610276               -1.574681   
 
           Age  Body Mass Index  Education  Children      Pets

In [69]:
#80-20 split
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,shuffle=True,random_state=42)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(560, 11) (560,)
(140, 11) (140,)


In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
reg=LogisticRegression()
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [71]:
print(reg.score(x_train,y_train))
print(reg.coef_)
print(reg.intercept_)

0.7732142857142857
[[ 2.91326793  0.75549599  3.1001126   0.96422678  0.07433973  0.65058443
  -0.2512894   0.25268283 -0.24135999  0.39883784 -0.29441037]]
[-1.7023427]


In [72]:
predict=reg.predict(x_train)
predict

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,

In [73]:
predict==y_train

array([ True,  True,  True,  True, False, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True, False, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [74]:
#Number of true prediction
print(f'Accuracy:{np.sum(predict==y_train)/predict.shape[0]}')

Accuracy:0.7732142857142857


In [75]:
summary=inputs.columns.values
summary

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [76]:
#Creating new dataframe table
#Transposing coefficients data -> Bcs ndarray is columns not rows
summary_table=pd.DataFrame(columns=['Features Name'],data=summary)
summary_table['Coefficients']=np.transpose(reg.coef_)
summary_table

Features Name  Coefficients
0                  Reason1      2.913268
1                  Reason2      0.755496
2                  Reason3      3.100113
3                  Reason4      0.964227
4                    Month      0.074340
5   Transportation Expense      0.650584
6                      Age     -0.251289
7          Body Mass Index      0.252683
8                Education     -0.241360
9                 Children      0.398838
10                    Pets     -0.294410

In [77]:
#Add 1 more index to the dataframe
#At row 0, give features name: intercept and value of intercept
#.sort_index() sorts table by index

summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Features Name  Coefficients
0                Intercept     -1.702343
1                  Reason1      2.913268
2                  Reason2      0.755496
3                  Reason3      3.100113
4                  Reason4      0.964227
5                    Month      0.074340
6   Transportation Expense      0.650584
7                      Age     -0.251289
8          Body Mass Index      0.252683
9                Education     -0.241360
10                Children      0.398838
11                    Pets     -0.294410

In [78]:
#Standardized Coefficients
summary_table['Odds Ratio']=np.exp(summary_table['Coefficients'])
summary_table

Features Name  Coefficients  Odds Ratio
0                Intercept     -1.702343    0.182256
1                  Reason1      2.913268   18.416885
2                  Reason2      0.755496    2.128667
3                  Reason3      3.100113   22.200451
4                  Reason4      0.964227    2.622759
5                    Month      0.074340    1.077173
6   Transportation Expense      0.650584    1.916661
7                      Age     -0.251289    0.777797
8          Body Mass Index      0.252683    1.287475
9                Education     -0.241360    0.785559
10                Children      0.398838    1.490092
11                    Pets     -0.294410    0.744971

In [79]:
#.sort_values('',ascending=False) sorts values in descending order

#Reason1: Various diseases
#Reason2: Pregnancy and giving birth
#Reason3: Poisoning
#Reason4: Light diseases
#Bias/Intercept--> Calibrates the model

summary_table.sort_values('Odds Ratio',ascending=False)

Features Name  Coefficients  Odds Ratio
3                  Reason3      3.100113   22.200451
1                  Reason1      2.913268   18.416885
4                  Reason4      0.964227    2.622759
2                  Reason2      0.755496    2.128667
6   Transportation Expense      0.650584    1.916661
10                Children      0.398838    1.490092
8          Body Mass Index      0.252683    1.287475
5                    Month      0.074340    1.077173
9                Education     -0.241360    0.785559
7                      Age     -0.251289    0.777797
11                    Pets     -0.294410    0.744971
0                Intercept     -1.702343    0.182256

.LogisticRegression.predict_proba(x) returns the probability estimates for all possible outputs

In [82]:
print(f'Test Accuracy:{reg.score(x_test,y_test)}')

Test Accuracy:0.7714285714285715


In [83]:
#COLUMN KIRI: Probabiity of being 0
#COLUMN KANAN: Probability of being 1

pred_prob=reg.predict_proba(x_test)
pred_prob

array([[0.82964265, 0.17035735],
       [0.85180287, 0.14819713],
       [0.79808463, 0.20191537],
       [0.59298483, 0.40701517],
       [0.57366649, 0.42633351],
       [0.08038046, 0.91961954],
       [0.67593146, 0.32406854],
       [0.35565538, 0.64434462],
       [0.71607461, 0.28392539],
       [0.73999951, 0.26000049],
       [0.86470554, 0.13529446],
       [0.67524315, 0.32475685],
       [0.26571911, 0.73428089],
       [0.44938817, 0.55061183],
       [0.72608771, 0.27391229],
       [0.49239272, 0.50760728],
       [0.8944988 , 0.1055012 ],
       [0.21436647, 0.78563353],
       [0.86716946, 0.13283054],
       [0.58401458, 0.41598542],
       [0.7303233 , 0.2696767 ],
       [0.74406231, 0.25593769],
       [0.68192133, 0.31807867],
       [0.67988009, 0.32011991],
       [0.86089273, 0.13910727],
       [0.16080983, 0.83919017],
       [0.59428914, 0.40571086],
       [0.59656673, 0.40343327],
       [0.7598924 , 0.2401076 ],
       [0.59939621, 0.40060379],
       [0.

In [84]:
pred_prob[:,1]

array([0.17035735, 0.14819713, 0.20191537, 0.40701517, 0.42633351,
       0.91961954, 0.32406854, 0.64434462, 0.28392539, 0.26000049,
       0.13529446, 0.32475685, 0.73428089, 0.55061183, 0.27391229,
       0.50760728, 0.1055012 , 0.78563353, 0.13283054, 0.41598542,
       0.2696767 , 0.25593769, 0.31807867, 0.32011991, 0.13910727,
       0.83919017, 0.40571086, 0.40343327, 0.2401076 , 0.40060379,
       0.11740886, 0.14124928, 0.599468  , 0.56109137, 0.27815375,
       0.64956431, 0.31807867, 0.13370072, 0.854817  , 0.19924262,
       0.51821218, 0.25191677, 0.63455821, 0.12801669, 0.2249606 ,
       0.72595153, 0.76914193, 0.8839772 , 0.30894311, 0.13040474,
       0.26000049, 0.31349281, 0.42633351, 0.93283037, 0.13869432,
       0.2249606 , 0.97638405, 0.27815375, 0.87185858, 0.22511208,
       0.59267817, 0.11962617, 0.49917611, 0.64434462, 0.13529446,
       0.41369029, 0.68015887, 0.05803339, 0.26971134, 0.50504807,
       0.26000049, 0.2401076 , 0.69842446, 0.31349281, 0.13410

In [85]:
pred_test=reg.predict(x_test)
pred_test

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0])

In [86]:
pred_test==y_test

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True, False,
        True, False, False,  True, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True, False,
        True,  True,  True, False,  True,  True, False, False, False,
        True, False,

In [87]:
print(f'Test Accuracy:{np.sum(pred_test==y_test)/pred_test.shape[0]}')

Test Accuracy:0.7714285714285715


pickle is a module used to convert a Python object into a character stream

In [88]:
#File Name: absenteesim_model
#wb: Write Bytes
#.dump= Save
#reg= object regression yg mau disimpen

import pickle
with open('absenteeism_model','wb')as file:
    pickle.dump(reg,file)

In [89]:
with open('absenteeism_scaler','wb')as file:
    pickle.dump(abs_scaler,file)