In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [18]:
#Load data from a text file
raw_data=np.loadtxt('Audiobooks_data.csv',delimiter=',')
print(raw_data)
print(raw_data.shape)

[[9.9400e+02 1.6200e+03 1.6200e+03 ... 5.0000e+00 9.2000e+01 0.0000e+00]
 [1.1430e+03 2.1600e+03 2.1600e+03 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [2.0590e+03 2.1600e+03 2.1600e+03 ... 0.0000e+00 3.8800e+02 0.0000e+00]
 ...
 [3.1134e+04 2.1600e+03 2.1600e+03 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [3.2832e+04 1.6200e+03 1.6200e+03 ... 0.0000e+00 9.0000e+01 0.0000e+00]
 [2.5100e+02 1.6740e+03 3.3480e+03 ... 0.0000e+00 0.0000e+00 1.0000e+00]]
(14084, 12)


In [19]:
#Semua Rows, Exclude row index 1 dan index -1 (Paling depan dan paling belakang)
unscaled_input=raw_data[:,1:-1]
print(unscaled_input)
print(unscaled_input.shape)

[[1620.   1620.     19.73 ... 1603.8     5.     92.  ]
 [2160.   2160.      5.33 ...    0.      0.      0.  ]
 [2160.   2160.      5.33 ...    0.      0.    388.  ]
 ...
 [2160.   2160.      6.14 ...    0.      0.      0.  ]
 [1620.   1620.      5.33 ...  615.6     0.     90.  ]
 [1674.   3348.      5.33 ...    0.      0.      0.  ]]
(14084, 10)


In [20]:
#Include semua rows, hanya index column terakhir yang di include
target=raw_data[:,-1]
print(target)
print(target.shape)

[0. 0. 0. ... 0. 0. 1.]
(14084,)


In [21]:
#Jumlahin semua total target yg ada di Data
one=int(np.sum(target))
zero=0
indices_remove=[]

print(one)

2237


In [22]:
#Target shape [0] is the length of vector
target.shape[0]

14084

In [23]:
for i in range(target.shape[0]):
    if target[i]==0:
        zero +=1
        if zero>one:
            indices_remove.append(i)

In [24]:
indices_remove

[2873,
 2874,
 2875,
 2876,
 2877,
 2878,
 2880,
 2881,
 2883,
 2885,
 2886,
 2887,
 2888,
 2889,
 2890,
 2891,
 2892,
 2894,
 2896,
 2898,
 2899,
 2900,
 2901,
 2902,
 2903,
 2904,
 2905,
 2906,
 2907,
 2908,
 2909,
 2910,
 2911,
 2912,
 2915,
 2916,
 2917,
 2918,
 2919,
 2920,
 2922,
 2923,
 2924,
 2925,
 2926,
 2928,
 2929,
 2930,
 2931,
 2932,
 2933,
 2934,
 2936,
 2937,
 2938,
 2940,
 2941,
 2942,
 2943,
 2944,
 2945,
 2946,
 2947,
 2948,
 2950,
 2951,
 2953,
 2954,
 2955,
 2956,
 2957,
 2958,
 2959,
 2960,
 2961,
 2964,
 2965,
 2966,
 2967,
 2968,
 2969,
 2970,
 2971,
 2972,
 2974,
 2975,
 2976,
 2977,
 2978,
 2979,
 2980,
 2981,
 2982,
 2984,
 2985,
 2986,
 2988,
 2989,
 2990,
 2991,
 2992,
 2993,
 2994,
 2995,
 2996,
 2998,
 2999,
 3000,
 3001,
 3003,
 3004,
 3005,
 3006,
 3007,
 3008,
 3009,
 3010,
 3011,
 3012,
 3013,
 3014,
 3015,
 3016,
 3017,
 3018,
 3019,
 3021,
 3022,
 3023,
 3024,
 3026,
 3027,
 3028,
 3029,
 3030,
 3031,
 3032,
 3033,
 3034,
 3035,
 3036,
 3037,
 3038,

np.delete(array,obj to delete,axis) is a method that deletes an object along an axis

In [25]:
new_unscaled=np.delete(unscaled_input,indices_remove,axis=0)
print(new_unscaled)
print(new_unscaled.shape)

[[1620.   1620.     19.73 ... 1603.8     5.     92.  ]
 [2160.   2160.      5.33 ...    0.      0.      0.  ]
 [2160.   2160.      5.33 ...    0.      0.    388.  ]
 ...
 [2160.   2160.      5.33 ...    0.      0.      6.  ]
 [1674.   3348.      7.99 ...    0.      0.      0.  ]
 [1674.   3348.      5.33 ...    0.      0.      0.  ]]
(4474, 10)


In [27]:
new_target=np.delete(target,indices_remove,axis=0)
print(new_target)
print(new_target.shape)

[0. 0. 0. ... 1. 1. 1.]
(4474,)


# Standardize Input & Target

preprocessing.scale(x) is a method that standardize arrays

In [28]:
scaled_inputs=preprocessing.scale(new_unscaled)
print(scaled_inputs)
print(scaled_inputs.shape)

[[ 0.21053387 -0.18888517  1.97823887 ...  4.80955413 11.83828419
   0.09415043]
 [ 1.27894497  0.41646744 -0.39082475 ... -0.41569922 -0.20183481
  -0.80255852]
 [ 1.27894497  0.41646744 -0.39082475 ... -0.41569922 -0.20183481
   2.979214  ]
 ...
 [ 1.27894497  0.41646744 -0.39082475 ... -0.41569922 -0.20183481
  -0.7440775 ]
 [ 0.31737498  1.7482432   0.04679395 ... -0.41569922 -0.20183481
  -0.80255852]
 [ 0.31737498  1.7482432  -0.39082475 ... -0.41569922 -0.20183481
  -0.80255852]]
(4474, 10)


In [29]:
scaled_inputs.shape[0]

4474

np.arange([start],stop) is a method that returns evenly spaced values within a given interval

In [30]:
#INDICES ITU NOMER/ID/ROWS
shuffled_indices=np.arange(scaled_inputs.shape[0])
shuffled_indices

array([   0,    1,    2, ..., 4471, 4472, 4473])

np.random.shuffle(X) is a method that shuffles the numbers in a given sequence

In [34]:
np.random.shuffle(shuffled_indices)

In [35]:
shuffled_inputs=scaled_inputs[shuffled_indices]
shuffled_targets=new_target[shuffled_indices]

In [37]:
print(shuffled_inputs)
print(shuffled_inputs.shape)

[[-0.64419501 -0.67316726  0.04843913 ... -0.41569922 -0.20183481
  -0.80255852]
 [-1.71260612 -1.27851988 -0.39082475 ... -0.41569922 -0.20183481
  -0.80255852]
 [ 0.31737498  1.7482432  -0.28059748 ... -0.41569922 -0.20183481
   0.10389727]
 ...
 [ 1.27894497  0.41646744 -0.16378948 ... -0.41569922 -0.20183481
  -0.80255852]
 [ 0.21053387 -0.18888517 -0.2888234  ... -0.41569922  2.20618899
   0.48402389]
 [ 0.21053387 -0.18888517  0.04843913 ... -0.41569922 -0.20183481
   0.2208593 ]]
(4474, 10)


In [38]:
print(shuffled_targets)
print(shuffled_targets.shape)

[0. 1. 1. ... 1. 1. 1.]
(4474,)


# Split Data

In [41]:
sample=shuffled_inputs.shape[0]
train=int(0.8*sample)
validation=int(0.1*sample)
test=sample-train-validation

print(train)
print(validation)
print(test)

3579
447
448


In [45]:
#[:3579] -> 3579 elemen pertama dalam list
train_input=shuffled_inputs[:train]
train_target=shuffled_targets[:train]

print(train_input.shape)
print(train_target.shape)

(3579, 10)
(3579,)


In [46]:
#[3579:4026]-> Elemen ke 3580 sampe ke 4026 jadi VALIDATION DATASET
validation_input=shuffled_inputs[train:train+validation]
validation_target=shuffled_targets[train:train+validation]

print(validation_input.shape)
print(validation_target.shape)

(447, 10)
(447,)


In [47]:
#[4026:]-> Semua elemen lain selain 4026 di awal
test_input=shuffled_inputs[train+validation:]
test_target=shuffled_targets[train+validation:]

print(test_input.shape)
print(test_target.shape)

(448, 10)
(448,)


In [49]:
#TARGET data vs INPUT data
#Target data di train, validation, test sama" di 49-52%
#Berarti data balanced
print(np.sum(train_target)/train)
print(np.sum(validation_target)/validation)
print(np.sum(test_target)/test)

0.4973456272701872
0.49440715883668906
0.5267857142857143


# Save Dataset

In [50]:
np.savez('Audiobook_train',inputs=train_input,targets=train_target)
np.savez('Audiobook_validation',inputs=validation_input,targets=validation_target)
np.savez('Audiobook_test',inputs=test_input,targets=test_target)