In [1]:
import numpy as np
#Row Vector
vector=np.array([-5,4,3])
print(vector)
print(vector.shape)
print(type(vector))

[-5  4  3]
(3,)
<class 'numpy.ndarray'>


In [2]:
#Scalar has 0 shape
scalar=np.array(5)
print(scalar)
print(scalar.shape)
print(type(scalar))

5
()
<class 'numpy.ndarray'>


In [3]:
matrix=np.array([[5,12,6],[-3,0,14]])
print(matrix)
print(matrix.shape)
print(type(matrix))

[[ 5 12  6]
 [-3  0 14]]
(2, 3)
<class 'numpy.ndarray'>


In [4]:
vector.reshape(1,3)

array([[-5,  4,  3]])

In [5]:
vector.reshape(3,1)

array([[-5],
       [ 4],
       [ 3]])

In [6]:
matrix2=np.array([[9,8,7],[-3,0,14]])
matrix2

array([[ 9,  8,  7],
       [-3,  0, 14]])

In [7]:
t=np.array([matrix,matrix2])
print(t)
print(t.shape)

[[[ 5 12  6]
  [-3  0 14]]

 [[ 9  8  7]
  [-3  0 14]]]
(2, 2, 3)


In [8]:
add_m=matrix+matrix2
print(add_m)
print(add_m.shape)

[[14 20 13]
 [-6  0 28]]
(2, 3)


In [9]:
subtract_m=matrix-matrix2
print(subtract_m)
print(subtract_m.shape)

[[-4  4 -1]
 [ 0  0  0]]
(2, 3)


In [10]:
vector1=np.array([1,2,3,4,5])
vector2=np.array([5,4,3,2,1])
subtract_v=vector1-vector2
print(subtract_v)
print(subtract_v.shape)

[-4 -2  0  2  4]
(5,)


In [11]:
add_v=vector1+vector2
print(add_v)
print(add_v.shape)

[6 6 6 6 6]
(5,)


# Transposing Vectors

array.T returns the transpose of an array

In [12]:
a=np.array([[5,12,6],[-3,0,14]])
print(a)
print(a.T)

[[ 5 12  6]
 [-3  0 14]]
[[ 5 -3]
 [12  0]
 [ 6 14]]


In [13]:
b=np.array([[4,3],[-2,4]])
print(b)
print(b.T)

[[ 4  3]
 [-2  4]]
[[ 4 -2]
 [ 3  4]]


In [14]:
c=np.array([[4,-5],[8,12],[-2,-3],[10,0]])
print(c)
print(c.T)

[[ 4 -5]
 [ 8 12]
 [-2 -3]
 [10  0]]
[[ 4  8 -2 10]
 [-5 12 -3  0]]


np.dot() returns the dot product of two objects

In [15]:
np.dot(vector1,vector2)

35

In [16]:
np.dot(5,6)

30

In [24]:
e=np.array([[5,12,6],[-3,0,14]])
print(e)
print(e.shape)
f=3*e
print(f)

[[ 5 12  6]
 [-3  0 14]]
(2, 3)
[[15 36 18]
 [-9  0 42]]


In [25]:
g=np.array([[2,-1],[8,0],[3,0]])
print(g)
print(g.shape)
h=np.dot(e,g)
print(h)
print(h.shape)

[[ 2 -1]
 [ 8  0]
 [ 3  0]]
(3, 2)
[[124  -5]
 [ 36   3]]
(2, 2)
